language: cpp

before_install:
  - export -f travis_fold
  - third-party/qt_installer/qt_installer.sh

install:
  # QtFtp
  - pushd third-party/qtftp
  - qmake CONFIG+=staticlib CONFIG+=c++11 CONFIG+=release
  - make
  - popd

  # QuaZIP
  - pushd third-party/quazip
  - qmake CONFIG+=staticlib CONFIG+=c++11 CONFIG+=release
  - make
  - popd

  # Fotorelacjonusz
  - ci/write_secrets_h.sh
  - lrelease fotorelacjonusz.pro
  - qmake CONFIG+=release LIBS+=-lz
  - make

script:
  - ${EXE} -v

before_deploy:
  # Set TRAVIS_TAG to "nightly" if blank (i.e. triggered by push to master).
  - export TRAVIS_TAG=${TRAVIS_TAG:-nightly}
  # Substitute TAG with $TRAVIS_TAG.
  - export PACKAGE_NAME="${PACKAGE_NAME/TAG/${TRAVIS_TAG}}"
  - git tag -a -f -m "Created by Travis" $TRAVIS_TAG
  - ci/package.sh

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: Pl1eq4L1Na7+2e9c3zEK3RG1a+CLR4b68k0ye2zl5h8z7wVVPPsn0FrfPvZZWk48jgI9HXDhR0zzctV1dh1ykZmowIZJZsBUguhlaIlyWsCSuCf1uIBXQG8naWu3AjJxefz8/KYF6aOJACU4sZFviW1e2vMtKF+Q6BXrjEhLQlc0pflTwBxOnlq2fTmt0uP9UuSP62Py0XbbaybAJAMEfSDb4lAZ5bwVXmOvCREP+vnSTlj/uiPxmw74jxYAmhX6kzgwN0i8XOwEjMSDmjtDyvr8dNN52GKDzpEt2R2UP8Z4ybYM7blyYj97GBi2ICPIh/IIE++R9qsMUDeR8OT28CVvrqd92cFZlNMC8YvTl4fvhzqJirWecGWqdCuhgSinMIIoplhqv48rtLtvrXHlNTSzFiElKodU2hbQrAjqZmFpugco21A3MreDt7BwL5HJvtr86bANpIqYuCOQNkpoNTpX1+4w6wwRAMv4Z5bhVbwkJK6Z8p3tJNBl9kBxfU5/YssOzY/x1pO9Ya14G6T0+YlH1+TNivPbfEPdNsSwXKKnH2A/CHZylQo0asmZV7ckDW3kAO2AASiYA3svi1IFMJUPASd01sQLwEGsZTTN8J6FKL9NauKd5QFtATTTOHRi0trARRak4L7lPI7E0LoGfzjOmIJn8dm43f+nMp4a8vU=
  on:
    repo: skalee/fotorelacjonusz
    all_branches: true
    condition: ("x${TRAVIS_TAG}" != "x") || ("${TRAVIS_BRANCH}" = master)
  file:
    - "${PACKAGE_NAME}"

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - EXE=./Fotorelacjonusz.app/Contents/MacOS/Fotorelacjonusz
        - PACKAGE_NAME="Fotorelacjonusz-TAG-macos.tar.gz"
        - PATH="/opt/Qt/5.12.3/clang_64/bin:${PATH}"
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/qt_installer_vars_mac.js"
